### ISSUE TITLE
[Index expression] does not apply to array returned by [?filter expression]

### ISSUE THREAD

**Issue by gmaFFFFF** [danielaparker/JsonCons.Net#9]
Hello,

`$.books[?@.price>22]` will return an book array: 
```
[
  {
    "category": "fiction",
    "title": "A Wild Sheep Chase",
    "author": "Haruki Murakami",
    "price": 22.72
  },
  {
    "category": "fiction",
    "title": "The Night Watch",
    "author": "Sergei Lukyanenko",
    "price": 23.58
  },
  {
    "category": "memoir",
    "title": "The Night Watch",
    "author": "David Atlee Phillips",
    "price": 260.90
  }
]
```

`$.books[?@.price>22][0]` will retrun an empty array `[]`
Many people think `$.books[?@.price>22][0]` **should return** a book:

```
{
    "category": "fiction",
    "title": "A Wild Sheep Chase",
    "author": "Haruki Murakami",
    "price": 22.72
}
```

It looks like this problem affects all similar libraries - [example](https://github.com/json-path/JsonPath/issues/272)

**Comment by danielaparker** [comment]
JSONPath basically collects values that are already in the original JSON document, it doesn't create new values, and as the last step, it appends all the values that it has collected into a result array. In JSONPath, the index operator can only be applied to items that are already arrays in the original JSON document, e.g., `$.books[0]`. The result array isn't created until all querying is done, it can't itself be queried against.

By contrast, there are other JSON query languages that do support the creation of new arrays as intermediate values, and these can be queried against. For example, the [JMESPath](https://jmespath.org/) expression

```
(books[?price > `8`])[0]
```
and the [JSONAta](https://jsonata.org/) expression

```
$.books[price > 8][0]
```

both produce
```
{
  "category": "fiction",
  "title": "A Wild Sheep Chase",
  "author": "Haruki Murakami",
  "price": 22.72
}
```

(JsonCons.Net has an implementation of JMESPath)

**Comment by gmaFFFFF** [comment]
Thanks for the clarification
